freifunk/meshviewer

lib/config_default.js

Add Missing D,
so D-Link DIR-615 D is also shown as deprecated

D-Link DIR-615 D, add missing 'D'

---

lib/config_default.js

The device won't be coming back either.
8mb flash, 32mb memory, ath79

Add deprecation warning for TL-WR1043N/ND v1

---

lib/config_default.js

Add deprecation warning for
* AVM FRITZ!Box 7320
* AVM FRITZ!Box 7330
* AVM FRITZ!Box 7330 SL
The devices have been dropped from gluon and are not likely to come back soon:
https://github.com/freifunk-gluon/gluon/commit/5231fb017800975bddaf655fa988055e007884be
Not at all.
This is the issue the devices have: https://github.com/freifunk-gluon/gluon/issues/1943

[TASK] Add deprecation warning for

---

lib/map.js

This was not yet fixed for using the json instead of a js file.
It works now, for example by adding the following to the config.json:
```
"geo": [
{
"json": [
{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
12.04925537109375,
49.036517514836994
],
[
12.033462524414062,
49.021660359632115
],
[
12.058181762695312,
48.99553703238219
],
[
12.11311340332031,
49.001843917978526
],
[
12.122726440429686,
49.03381654386847
],
[
12.04925537109375,
49.036517514836994
]
]
]
}
}
],
"option": {
"style": {
"color": "#e23535",
"weight": 5,
"opacity": 0.4,
"fillColor": "#6de922",
"fillOpacity": 0.1
}
}
}
],
```
This allows to define polygons as overlay for borders
Define the given snippet in the config.json
This is a followup PR for …

[BUGFIX] Allow defining geojson in config.json

---

package-lock.json
package.json

@skorpy2009 broke it during updates, this should fix it temporarily
Fixing stuff
Local dev env
-

[BUGFIX] Revert "npm: bump navigo from 7.1.3 to 8.11.1" as that change breaks the map (duh)

---

lib/proportions.js
locale/cz.json
locale/de.json
locale/en.json
locale/fr.json
locale/ru.json
locale/tr.json

This adds a filter option for deprecationStatus and Base Version (mostly gluon base version, but also Debian/Ubuntu for supernodes)
fixes #14 
fixes https://github.com/ffrgb/meshviewer/issues/334
From FFAC domain:

[TASK] adds filter for deprecationStatus and baseversion

---

config.json.example
lib/infobox/node.js
lib/utils/helper.js
scss/modules/_base.scss

This adds the option to set an url where hardware images can be fetched from.
These are then shown per router, as can be seen here:
This is a very nice feature which is available in hopglass but wasn't available in meshviewer until now.
It helps to recognize how the router looks like.
To create an image source, one can either use existing ones like:
`https://cdn.rawgit.com/Moorviper/meshviewer_hwpics/master/nodes/{MODEL_HASH}.svg`
`https://map.eulenfunk.de/nodes/{MODEL_HASH}.svg`
or a [bash script as described here](https://forum.freifunk.net/t/mithilfe-aufruf-aktuelle-firmware-selector-bilder/23821/4)
`https://map.aachen.freifunk.net/router-images/{MODEL_NORMALIZED}.svg`
This patchset is currently active in Aachen, see:
https://map.aachen.freifunk.net

[TASK] Hardware images for routers on the map

---

lib/infobox/node.js

This changes the MODEL_NORMALIZED for devices with a dot in their model name.
This reflects the firmware upgrade conversion, which is also allowed to have a dot in the file name.
For example: `gl.inet-gl-ar300m` or `raspberry-pi-model-b-plus-rev-1.2`
This makes it easier to provide the same image source
WIP

[BUGFIX] a dot is allowed in firmware image names

---

config.example.json
lib/about.js
lib/gui.js
lib/infobox/node.js
lib/utils/helper.js
public/locale/de.json
public/locale/en.json

This adds attribution of the hardware images to the about page.
A rename from hwImg to device_pictures is done.
It is possible to change to a  custom attribution if a different source of pictures is taken.
The CC-BY-NC-SA 4.0 requires to attribute the creators.
As we are all not lawyers this is a first step into this direction.
I do not think that it is required to attribute per picture, but we should make such information available in the https://github.com/freifunk/device-pictures repository.
See https://map.aachen.freifunk.net/

[TASK] add attribution of device-pictures to about page

---

index.html
offline.html
vite.config.js

The previous version before the migration to vite (860cdd9) allowed deployment to any subdirectory (e.g. `/meshviewer/`).
Vite defaults to a base path starting in the url's root: https://vitejs.dev/config/shared-options.html#base
Wanted to verify the latest build for https://www.freifunk-gera-greiz.de/meshviewer/ but got a bunch of 404 errors.

[BUGFIX] Fix deployment to subfolders

---

.github/dependabot.yml
.github/workflows/build-docker.yml
.github/workflows/publish-docker.yml
Dockerfile

Adds docker support & proper workflows to automatically build the image.
More and more communities are using Docker in their deployments. This makes it possible to package meshviewer as a docker image.
In the dev environment over at https://github.com/freifunkMUC/meshviewer
- [n/a] My change requires a change to the documentation.
- [n/a] I have updated the documentation accordingly.

feat: Docker builds

---

lib/config_default.ts

These are deprecated as of https://gluon.readthedocs.io/en/v2022.1/releases/v2022.1.html#removed-devices
I'd like to show this banner for the sole device in FFAC too ;)

[BUGFIX] add WD My Net devices to deprecation

---

lib/simplenodelist.ts

The actual fix is saving the patched node.
This effectively reverts (part of)
https://github.com/freifunk/meshviewer/commit/005130988965a1ae60f6e83556dce53dc7d2ce75
So the simplest fix would be:
```ts
patch(tbody, tbodyNew)
```
->
```ts
tbody = patch(tbody, tbodyNew) as unknown as HTMLTableSectionElement;
```
(however the typing is anyway wrong here, but that doesn't really matter here)
I am not really sure why thats relevant for patch, but I could not get it working without.  
I thought that the patch always replaces the "diff", but maybe I don't understand Snabbdom correctly^^
Also I also noticed that there is an edge case when on the first load the list shows no nodes
and in subsequent reloads it gets nodes, it will append the node list always at the bottom, which may not be correct. …

[BUGFIX] Fix SimpleNodelist to replace instead of appending new nodes.

---

package-lock.json
package.json

npm: update sass to 1.77.8
version of https://github.com/freifunk/meshviewer/pull/144 without deprecation warnings, updating only so far it doesn't yield warnings
local test setup
-/-

npm: update sass to 1.77.8

---

lib/sorttable.ts

Similar problem as #149.
However I think I understand it now better:
the example on https://github.com/snabbdom/snabbdom describes that the first patch should be on the dom-element, but the second patch should be on the vnode from before.
So it now saves the last vnode and patch it. Only on the first patch (if vnode is not set yet), it patches the element.
Closes #137 
FF and chrome, mobile and desktop tested

[BUGFIX] sorting of sortable tables. (#137)

---

lib/proportions.ts
lib/utils/version.ts

Before, the firmware were not sorted if the count is the same.
This is fixed with this PR.
Furthermore, a leading v is stripped of the version string when comparing to fix wrong orders.
closes #90

sort firmware versions by name if same count exists

---

lib/about.ts
lib/global.d.ts
vite.config.js

add version info on the about page.
This is implemented as a global variable, so that is is automagically adjusted with the package.json version
also remove old fork information
It is sometimes not directly visible which meshviewer version is used.
The fork and maintenance information is outdated, so I removed it.

add version info on about page

---

lib/proportions.ts

before, the nodes used for the stats were only all online plus lost nodes. This amount is filtered by maxage, which is confusing and unexpected
This led to issues at @freifunkh, as they do not have a matching age filter in yanic to their meshviewer config.
The `maxAge` config param now only filters the "new Nodes" and "disappeared Nodes" view.
This issue also exists on graveyard configs, which do not limit the old nodes
Run code locally using `npm run dev` and `npm run build`

fix: calculate stats on all nodes

---

scss/modules/_map.scss

On modern browsers, the lower browser bar hides parts of the lower sidebar, making it hard to scroll to the sidebar.
This is fixed by reducing the size of the map to 80% of the viewport instead of depending on 150px
@grische mentioned this issue on his phone yesterday

feat: increase height of info sidebar on small mobile screens

---

vite.config.js

This fixes the PWA to not return the application on *.json files.
The issue appears when visiting the config.json of any meshviewer.
Using curl/wget, one receives the valid json, but in a browser with Service-Worker, the application is returned instead.
This is fixed with this config change.
Besides of the config.json, there is also the `locale/en.json` and thelike, which should not be handled by the service worker as well.
Instead, they are now correctly served by the browser cache.
visit /config.json after visiting the application in a private tab.
Before, this did show the meshviewer as well.
Run `npm run build` and `python -m http.server 8089 -d build` to serve this, as the dev server does not have this issue.

fix: loading the json file did create a root application instead returning the cached json

---

.github/workflows/release-meshviewer.yml

as noted in https://github.com/freifunk/meshviewer/pull/184#issuecomment-3018478131, it is better to use a fixed commit version.

ci: use a fixed action-gh-release version for thirdparty release action

---

lib/map/button.js

always zooming back to the user location is quite annoying when wanting to zoom out and changing the view. This is especially useful when viewing your location in relation to a different router.
When having the position activated, a blue marker for the position is shown. This marker always resets the view and zoom after a few seconds to the position.
I don't think that this is the expected behavior.

feat: disable location watching

---

README.md
config.example.json
lib/config_default.ts
lib/infobox/node.ts
lib/proportions.ts
public/locale/de.json
public/locale/en.json
scss/modules/_base.scss
scss/modules/_variables.scss

Adding a separation between EOL and Deprecated devices.
Adding a separation as 4/32 devices have already reached EOL a while ago and will not be "soon loose support", while at the same time, we have candidates that might loose support soon.
https://map.ffmuc.net as part of https://github.com/freifunkMUC/meshviewer/pull/70
See https://map.ffmuc.net
This PR resolves #75

separate EOL and deprecated devices

---

lib/utils/node.ts
public/locale/de.json

This fixes the information shown for firstseen
When switching from english to german in an english browser, the english local was used:
This is fixed with this PR.
Furthermore, the correct past prefix is added for the first seen - printing "vor 21 Tagen" as well as in english

fix: firstseen now respects locale and shows a past time

---

tsconfig.json

this is required for compatibility with client libraries which are imported differently
This fixes the problems with other libraries we encountered in #132 and #74

npm: fix tsconfig

---

lib/global.d.ts
lib/main.ts
lib/utils/language.ts
lib/utils/router.ts
package-lock.json
package.json
tsconfig.json

Refactor router to be class based, update navigo based on #36, updated vite to fix annoying warning of empty source maps

Refactor Router
